
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Patrick
 */
public class MainGUI extends javax.swing.JFrame {

    private Auction auction;
    private GUIHandler gh;

    public MainGUI(GUIHandler gh, Auction auction) {
        this.gh = gh;
        this.auction = auction;

        initComponents();
        setFrameSettings();

        auctionOverview_Set(auction.getLots());
    }

    public void setFrameSettings() {
        setLocationRelativeTo(null);
    }

    public void updateFields() {
        String lotN = auctionOverview_getSelected();
        Lot l = auction.getTheLot(Integer.parseInt(lotN));
        Bid b = l.getHighestBid();

        auctionNumber_Set(Integer.toString(l.getNumber()));
        if (b != null) {
            auctionHighBid_Set(Long.toString(l.getHighestBid().getValue()));
        } else {
            auctionHighBid_Set("No highest bid");
        }
        if (b != null) {
            auctionBidder_Set(l.getHighestBid().getBidder().getName());
        } else {
            auctionBidder_Set("No bidder");
        }
        auctionDescription_Set(l.getDescription());
    }

    public String auctionOverview_getSelected() {
        try {
            return auctionOverview_JList.getSelectedValue().toString();
        } catch (NullPointerException e) {
            return null;
        }
    }

    public void auctionOverview_Set(ArrayList<Lot> lots) {
        DefaultListModel dlm = new DefaultListModel();
        for (Lot l : lots) {
            dlm.addElement(l.getNumber());
        }
        auctionOverview_JList.setModel(dlm);
    }

    public void auctionNumber_Set(String s) {
        auctionNumber_JTextField.setText(s);
    }

    public void auctionHighBid_Set(String s) {
        auctionHighBid_JTextField.setText(s);
    }

    public void auctionBidder_Set(String s) {
        auctionBidder_JTextField.setText(s);
    }

    public void auctionDescription_Set(String s) {
        auctionDescription_JTextArea.setText(s);
    }

    public void selectionReset() {
        try {
            if (!auctionOverview_JList.isSelectionEmpty()) {
                auctionOverview_JList.setListData(new Object[0]);
            }
        } catch (NumberFormatException e) {}
        auctionNumber_Set("");
        auctionBidder_Set("");
        auctionHighBid_Set("");
        auctionDescription_Set("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        auctionOverview_JList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        auctionNumber_JTextField = new javax.swing.JTextField();
        auctionHighBid_JTextField = new javax.swing.JTextField();
        auctionBidder_JTextField = new javax.swing.JTextField();
        makeABid_JButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        auctionDescription_JTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        amMenu = new javax.swing.JMenu();
        createAuction_MenuItem = new javax.swing.JMenuItem();
        deleteAuction_MenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auction");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        auctionOverview_JList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "hej", "tis", "prut", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        auctionOverview_JList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        auctionOverview_JList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                auctionOverview_JListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(auctionOverview_JList);

        jLabel2.setText("Number");

        jLabel3.setText("Highest bid");

        jLabel4.setText("Bidder");

        auctionNumber_JTextField.setEditable(false);

        auctionHighBid_JTextField.setEditable(false);

        auctionBidder_JTextField.setEditable(false);

        makeABid_JButton.setText("Make a bid");
        makeABid_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeABid_JButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Description");

        auctionDescription_JTextArea.setBackground(new java.awt.Color(240, 240, 240));
        auctionDescription_JTextArea.setColumns(20);
        auctionDescription_JTextArea.setRows(5);
        jScrollPane2.setViewportView(auctionDescription_JTextArea);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(auctionNumber_JTextField)
                            .addComponent(auctionHighBid_JTextField)
                            .addComponent(auctionBidder_JTextField)
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(makeABid_JButton)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(auctionNumber_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(auctionHighBid_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(auctionBidder_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makeABid_JButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        amMenu.setText("Auction management");

        createAuction_MenuItem.setText("Create auction");
        createAuction_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAuction_MenuItemActionPerformed(evt);
            }
        });
        amMenu.add(createAuction_MenuItem);

        deleteAuction_MenuItem.setText("Delete auction");
        deleteAuction_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAuction_MenuItemActionPerformed(evt);
            }
        });
        amMenu.add(deleteAuction_MenuItem);

        menuBar.add(amMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    }//GEN-LAST:event_formWindowActivated

    private void auctionOverview_JListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_auctionOverview_JListValueChanged
        updateFields();
    }//GEN-LAST:event_auctionOverview_JListValueChanged

    private void makeABid_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeABid_JButtonActionPerformed
        String lot_String = this.auctionOverview_getSelected();
        if (lot_String != null) {
            int lot_int = Integer.parseInt(lot_String);
            Lot lot = auction.getTheLot(lot_int);
            gh.createMakeABidGUI(lot);
        }
    }//GEN-LAST:event_makeABid_JButtonActionPerformed

    private void createAuction_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAuction_MenuItemActionPerformed
        gh.createCreateAuctionGUI();
    }//GEN-LAST:event_createAuction_MenuItemActionPerformed

    private void deleteAuction_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAuction_MenuItemActionPerformed
        gh.createDeleteAuctionGUI();
    }//GEN-LAST:event_deleteAuction_MenuItemActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainGUI().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu amMenu;
    private javax.swing.JTextField auctionBidder_JTextField;
    private javax.swing.JTextArea auctionDescription_JTextArea;
    private javax.swing.JTextField auctionHighBid_JTextField;
    private javax.swing.JTextField auctionNumber_JTextField;
    private javax.swing.JList auctionOverview_JList;
    private javax.swing.JMenuItem createAuction_MenuItem;
    private javax.swing.JMenuItem deleteAuction_MenuItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton makeABid_JButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
